[modules/authentication_saml] Add assertion parsing [PREVIEW]
coopengo/tryton pull request #102
Opened 2023-12-06 08:58 UTC by JCavallo

Fix PCLAS-466

2023-12-06 11:05 UTC, nicoe commented on modules/authentication_saml/routes.py
> +    authn_response.parse_assertion()
Je vois que la méthode peut recevoir un paramètre `key`. J'imagine bien que tu n'en as pas eu besoin.
Néanmoins je me demande, ne faudrait il pas le prévoir dans la configuration du module si on en a besoin ?
Et si oui, où ? Plus probablement dans la configuration de pysaml2 mais alors il faut prévoir du code pour aller récupérer cette info.

Enfin soit, c'est en dehors du scope de ce patch j'imagine mais je vais creuser le sujet.

2023-12-06 11:05 UTC, nicoe approved these changes

2023-12-06 12:54 UTC, nicoe commented on modules/authentication_saml/routes.py
> +    authn_response.parse_assertion()
Bon après check dans le code, le None va utiliser une valeur par défaut qui est spécifiée dans le fichier de config en python qui peut être passé à pysaml2 (cfr https://pysaml2.readthedocs.io/en/latest/howto/config.html#encryption-keypairs pour la doc)

2023-12-06 13:39 UTC, nicoe requested changes
En fait, je crois que cette ligne n'est pas nécessaire si tout se passe correctement auparavant.

En effet, lors de l'appel `Base._parse_response` (le client hérite de `Base`), un appel à `response.verify` est effectué, appel qui lui même fait un `parse_assertion`.

2023-12-07 07:50 UTC, JCavallo commented
@nicoe mais dans ce cas il devrait y avoir une erreur au moment de `_parse_response` / `verify`, non ?

2023-12-11 08:36 UTC, closed without merging