electronic_signature: more explit message when error comes from provider
coopengo/tryton pull request #31
Opened 2023-08-30 13:48 UTC by sleibo-coopengo

Fix PROCK-641

2023-08-30 13:52 UTC, sleibo-coopengo commented
Test avec un serveur HTTP qui renvoie une erreur : 

![image](https://github.com/coopengo/tryton/assets/56913865/c2da47f4-488b-4e16-9776-d7dcc37173ac)

2023-08-30 13:56 UTC, SylvainEmonet commented
Impec merci :)

2023-08-30 14:05 UTC, PierreCookie commented
On évincerais pas la stack d'erreur ?

2023-08-30 14:27 UTC, sleibo-coopengo commented
> On évincerais pas la stack d'erreur ?

Je pense que ça peut toujours être utile de connaître l'appel qui a provoqué l'erreur (ici update_transaction_info)

![Uploading image.png…]()

2023-08-31 07:23 UTC, sleibo-coopengo commented
Message d'erreur plus présentable : 

![image](https://github.com/coopengo/tryton/assets/56913865/7c26cbeb-0e64-49f3-ab92-3988f0b4588e)

2023-08-31 08:01 UTC, PierreCookie reviewed
@coopengo/coogcore

2023-08-31 08:01 UTC, PierreCookie commented on coopengo_modules/electronic_signature/message.xml
> +            <field name="text">The signature service returned the following error</field>
```suggestion
            <field name="text">The signature service returned the following error:\n%(trace)s</field>
```

2023-08-31 08:01 UTC, PierreCookie commented on coopengo_modules/electronic_signature/locale/fr.po
> +msgstr "Le service de signature a renvoyé l'erreur suivante"
```suggestion
msgid "The signature service returned the following error:\n%(trace)s"
msgstr "Le service de signature a renvoyé l'erreur suivante :\n%(trace)s"
```

2023-08-31 08:01 UTC, PierreCookie commented on coopengo_modules/electronic_signature/signature.py
> +            raise UserError(prefix_msg + ':\n\n' + req.content.decode('utf8'))
```suggestion
            raise UserError(gettext('electronic_signature.msg_provider_error', trace=req.content))
```

2023-08-31 15:42 UTC, PierreCookie approved these changes

2023-09-04 12:57 UTC, jmousset commented on coopengo_modules/electronic_signature/signature.py
> +                    trace=req.content.decode('utf8')))
j'aurais bien vu un check sur l'existence ou non de req.content.  et sauf erreur req.text gère l'encoding pour l'utilisateur.

2023-09-04 15:13 UTC, sleibo-coopengo commented on coopengo_modules/electronic_signature/signature.py
> +                    trace=req.content.decode('utf8')))
Done

S'il n'y a pas de contenu, le statut HTTP est affiché :

![image](https://github.com/coopengo/tryton/assets/56913865/9660ce18-7775-432e-b728-f14a05518b69)

2023-09-04 15:45 UTC, jmousset submitted a review, later dismissed

2023-09-05 07:03 UTC, PierreCookie approved these changes

2023-09-05 07:40 UTC, JCavallo requested changes

2023-09-05 07:40 UTC, JCavallo commented on coopengo_modules/electronic_signature/signature.py
> +                    trace=(req.text if req.text else req.status_code))
Pour moi il ne faut pas afficher d'informations techniques aux utilisateurs : logger l'erreur, voire éventuellement pour passer par l'error handler pour stocker le contenu de l'erreur si besoin

2023-09-06 08:55 UTC, sleibo-coopengo commented
### Tests après dernières modifications : 

![image](https://github.com/coopengo/tryton/assets/56913865/86671d5e-6662-416b-88a0-a3b4db990a98)

![image](https://github.com/coopengo/tryton/assets/56913865/87ae23e5-08cf-4466-a410-1469c199c503)

2023-09-06 09:01 UTC, sleibo-coopengo commented on coopengo_modules/electronic_signature/signature.py
> +            cls.logger.info(f'{message} : {req.status_code} - {req.text}')
J'ai mis le niveau INFO car ce n'est pas une erreur Coog mais une info comme quoi le serveur a renvoyé une erreur

2023-09-06 12:16 UTC, SylvainEmonet commented
En faisant ça, on perd de la visibilité côté support : les logs en Prod sont en WARNING + le message d'erreur a été tellement réduit (je trouve ça dommage) depuis le début de la PR que maintenant on n'a même pas l'erreur renvoyée par le service externe. A mon avis, il vaut mieux mettre le plus de détails pour que ça parle au plus de monde plutôt que de réduire comme ça.
Merci

2023-09-06 15:45 UTC, jmousset reviewed
@JCavallo voir la remarque de sylvain.

2023-09-06 15:45 UTC, jmousset commented on coopengo_modules/electronic_signature/signature.py
> +            cls.logger.info(f'{message} : {req.status_code} - {req.text}')
certes mais on va chercher des erreurs dans les logs quand on aura ce genre de souci.

2023-09-07 08:29 UTC, sleibo-coopengo commented
Suite discussions : 

* Message d'erreur :  ![image](https://github.com/coopengo/tryton/assets/56913865/f8284107-da5d-4018-885d-9f1810390105)
* Logs d'erreur de la signature : HTTP Status + contenu de la réponse serveur
![image](https://github.com/coopengo/tryton/assets/56913865/9b582d98-f05a-4780-a7c8-5f240f52a569)
*Logs Serveur Coog : HTTP Status + contenu de la réponse serveur : 
![image](https://github.com/coopengo/tryton/assets/56913865/86ae41f7-3c95-4f36-8f8d-09a7bac2f125)


@SylvainEmonet @JCavallo @PierreCookie OK pour vous (avant que je committe) ?

2023-09-07 09:56 UTC, jmousset approved these changes

2023-09-07 12:08 UTC, PierreCookie approved these changes

2023-09-07 12:48 UTC, JCavallo approved these changes

2023-09-07 14:32 UTC, merged