Don't reset dates to None when the date is invalid
coopengo/tryton pull request #7
Opened 2023-07-10 08:29 UTC by nicoe

PCLAS-209
PCLAS-219

2023-07-10 14:11 UTC, JCavallo reviewed
Ça m'a l'air ok sur sao par contre

2023-07-10 14:11 UTC, JCavallo commented on tryton/tryton/gui/window/view_form/screen/screen.py
> +                fields.append(_('The value of "%s" is not valid.') % string)
Test rapide dans un wizard ko.

Il reste du code dans `tryton/common/datetime_@date_parse` qui `try` / `except` tout.
Et en l'enlevant, j'ai ça en popup :

```
2023-07-10 16:09:15.311:ERROR:NoneType: None

TypeError: Object of type InvalidDateTime is not JSON serializable
```

2023-07-12 07:24 UTC, JCavallo commented
C'est mieux.

Par contre on avait une feature sympa qui a disparue : quand on faisait une saisie `010123` ou `01012023`, c'était accepté, et ce n'est plus le cas là...

2023-07-12 15:43 UTC, nicoe commented
> C'est mieux.
> 
> Par contre on avait une feature sympa qui a disparue : quand on faisait une saisie `010123` ou `01012023`, c'était accepté, et ce n'est plus le cas là...

En fait `dateutil` ne parse pas correctement les dates dans le format DDMMYYYY, j'ai fait un patch pour que ça fonctionne mais ça ne m'a plus l'air fort maintenu :( https://github.com/dateutil/dateutil/pull/1296

Je suis donc en train de faire en parallèle un bout de code pour supporter ce cas en spécifique.

2023-07-17 07:23 UTC, JCavallo commented
Ne fonctionne pas chez moi, toujours dans un wizard (un 01012001 reste "en rouge").

En lisant vite fait le code, tu parses un `20010101` et pas un `01012001,

2023-08-07 14:42 UTC, JCavallo requested changes
Avec `01012001` :

```  File "/home/jean.cavallo/Projets/Coog/Envs/master/tryton/tryton/tryton/gui/window/view_form/view/form_gtk/widget.py", line 90, in get_value
    GLib.timeout_add(300, send, self.get_value())
  File "/home/jean.cavallo/Projets/Coog/Envs/master/tryton/tryton/tryton/gui/window/view_form/view/form_gtk/calendar_.py", line 77, in get_value
    self.entry.parse()
  File "/home/jean.cavallo/Projets/Coog/Envs/master/tryton/tryton/tryton/common/datetime_.py", line 130, in parse
    self.__date = date_parse(text, self.__format).date()

AttributeError: 'datetime.date' object has no attribute 'date'```

2023-08-09 13:01 UTC, closed without merging